version: '2.1'

services:
    greenplum_4.3:
      # jdbc:postgresql://localhost:54302/gpadmin?user=gpadmin&password=pivotal
      container_name: greenplum_4.3
      ports:
        - "54302:5432"
      image: datagrip/greenplum
      healthcheck:
        test: grep -r -i --include \*.log "Database successfully started" || exit 1
        interval: 20s
        timeout: 10s
        retries: 5

    mysql_5.7_ssl:
      # jdbc:mysql://localhost:33057/guest?user=guest&password=guest
      container_name: mysql57ssl
      ports:
        - "33777:3306"
      image: datagrip/mysqlssl
      env_file: .env
      command: [mysqld, --character-set-server=utf8, --collation-server=utf8_unicode_ci]
      healthcheck:
        test: "exit 0"

    memsql_6.7:
      # jdbc:mysql://localhost:33088/guest?user=guest&password=guest
      container_name: memsql_6.7
      image: datagrip/memsql:6.7
      ports:
        - "33088:3306"
      env_file: ./experimental.env
      environment:
        - IGNORE_MIN_REQUIREMENTS=1
      healthcheck:
        test: "exit 0"

    maria_10.2.7:
      # jdbc:mariadb://localhost:33127/guest?user=guest&password=guest
      container_name: maria_10.2.7
      image: mariadb:10.2.7
      ports:
        - "33127:3306"
      env_file: .env
      command: [mysqld, --character-set-server=utf8, --collation-server=utf8_unicode_ci]
      healthcheck:
        test: "exit 0"

    maria_10.2.4:
      # jdbc:mariadb://localhost:33124/guest?user=guest&password=guest
      container_name: maria_10.2.4
      image: datagrip/mariadb:10.2.4
      ports:
        - "33124:3306"
      env_file: .env
      command: [mysqld, --character-set-server=utf8, --collation-server=utf8_unicode_ci]
      healthcheck:
        test: "exit 0"

    maria_10.2.5:
      # jdbc:mariadb://localhost:33125/guest?user=guest&password=guest
      container_name: maria_10.2.5
      image: mariadb:10.2.5
      ports:
        - "33125:3306"
      env_file: .env
      command: [mysqld, --character-set-server=utf8, --collation-server=utf8_unicode_ci]
      healthcheck:
        test: "exit 0"

    maria_10.3.8:
      # jdbc:mariadb://localhost:33138/guest?user=guest&password=guest
      container_name: maria_10.3.8
      image: mariadb:10.3.8
      ports:
        - "33138:3306"
      env_file: .env
      command: [mysqld, --character-set-server=utf8, --collation-server=utf8_unicode_ci]
      healthcheck:
        test: "exit 0"

    # oracle 11.2.0.2 express edition (official)
    oracle_11.2_xe:
      container_name: oracle_11.2_xe
      ports:
        - "15112:1521"
      image: datagrip/oracle:11.2.0.2-xe
      shm_size: 1g
      env_file: .env

    hsqldb_2.0:
      container_name: hsqldb_2.0
      image: datagrip/hsqldb:2.0.0
      ports:
        - "9001:9001"
      env_file: ./experimental.env
      healthcheck:
        test: "exit 0"

    hsqldb_2.3.3:
        container_name: hsqldb_2.3.3
        image: datagrip/hsqldb:2.3.3
        ports:
        - "9002:9001"
        env_file: ./experimental.env
        healthcheck:
          test: "exit 0"

    derby_10.11:
      container_name: derby_10.11
      image: datagrip/derby-server:10.11
      ports:
        - "1527:1527"
      env_file: .env
      healthcheck:
        test: "exit 0"

    derby_10.12:
      container_name: derby_10.12
      image: datagrip/derby-server:10.12
      ports:
        - "1528:1527"
      env_file: .env
      healthcheck:
        test: "exit 0"

    h2_1.3:
      container_name: h2_1.3
      image: datagrip/h2:1.3
      ports:
        - "9092:9092"
      env_file: .env
      healthcheck:
        test: "exit 0"

    # IBM Informix Innovator-C
    informix_12.10:
      container_name: informix_12.10
      privileged: true
      image: ibmcom/informix-innovator-c:12.10.FC11IE
      ports:
        - "9088:9088"
        - "27017:27017"
        - "27018:27018"
      env_file: .env
      healthcheck:
        test: "exit 0"

    iris_2019:
      container_name: iris_2019
      image: datagrip/iris:2019
      ports:
        - "9092:52773"
        - "9091:51773"
      env_file: .env
      command: -p /durable/iris.txt
      healthcheck:
        test: grep -r "Private webserver started on 52773" /usr/irissys/mgr/messages.log
        interval: 2m
        timeout: 10s
        retries: 5

    firebird_3:
      # jdbc:firebirdsql://localhost:3050/guest?encoding=UTF8
      container_name: firebird_3
      image: jacobalberty/firebird:3.0
      ports:
        - "3050:3050"
      environment:
        ISC_PASSWORD: firebird25ss
        FIREBIRD_DATABASE: guest
        FIREBIRD_USER: guest
        FIREBIRD_PASSWORD: guest
      healthcheck:
        test: "exit 0"

    firebird_2.5_sc:
      # jdbc:firebirdsql://localhost:3052//firebird/data/guest?encoding=UTF8
      container_name: firebird_2.5_sc
      image: jacobalberty/firebird:2.5-sc
      ports:
        - "3052:3050"
      environment:
        FIREBIRD_DATABASE: guest
        FIREBIRD_USER: guest
        FIREBIRD_PASSWORD: guest
      healthcheck:
        test: "exit 0"


    saphana_2:
      # user: SYSTEM
      # pwd: HXEHana1
      # jdbc:sap://localhost:39017/
      container_name: saphana_2
      image: store/saplabs/hanaexpress:2.00.033.00.20180925.2
      ports:
        - "39017:39017"
      ulimits:
        nofile:
          soft: 1048576
          hard: 1048576
      sysctls:
        - kernel.shmmax=1073741824
        - kernel.shmmni=524288 
        - kernel.shmall=8388608
      command: --agree-to-sap-license --passwords-url http://download.labs.intellij.net/idea/jdbc-drivers/file.json
      healthcheck:
        test: grep -ris --include \*.log "SAP HANA instance executed"
        interval: 4m
        timeout: 5s
        retries: 3

    pg_postgis:
      container_name: pg_postgis
      image: datagrip/postgis
      ports:
        - "32222:5432"
      env_file: .env
      healthcheck:
        test: "exit 0"

    #docker run -e DB_USER=test -e DB_PASSWORD=test -e DB_NAME=test -e REP_USER=rtest -e REP_PASSWORD=test -e ROLE=master --name pg-master -p 5432 -d hmarr/postgresql
    #docker run -e DB_USER=test -e DB_PASSWORD=test -e DB_NAME=test -e REP_USER=rtest -e REP_PASSWORD=test -e ROLE=slave -e MASTER_HOST=$MASTER_HOST -e MASTER_PORT=5432 --name pg-slave -p 5432 -d hmarr/postgresql
    pg_master:
      container_name: pg-master
      image: hmarr/postgresql
      ports: 
        - "32768:5432"
      environment:
        - DB_USER=test
        - DB_PASSWORD=test
        - DB_NAME=test
        - REP_USER=rtest
        - REP_PASSWORD=test
        - ROLE=master
      healthcheck:
        test: "sleep 10 || true"
        interval: 1m
        timeout: 5s
        retries: 3

    pg_slave:
      container_name: pg-slave
      image: hmarr/postgresql
      ports:
        - "32769:5432"
      depends_on:
        - pg_master
      external_links:
        - pg_master
      environment:
        - DB_USER=test
        - DB_PASSWORD=test
        - DB_NAME=test
        - REP_USER=rtest
        - REP_PASSWORD=test
        - ROLE=slave
        - MASTER_PORT=5432
        - MASTER_HOST=pg_master
      healthcheck:
        test: "sleep 5 || true"
        interval: 1m
        timeout: 5s
        retries: 3