version: '2.1'

services:
  pg_9.3_ssl:
    container_name: pg_9.3_ssl
    build: ./ssl/pg/9.3/
    ports:
      - "54323:5432"
    env_file: .env
    healthcheck:
      test: "exit 0"
  pg_9.5_ssl:
    container_name: pg_9.5_ssl
    build: ./ssl/pg/9.5/
    ports:
      - "54325:5432"
    env_file: .env
    healthcheck:
      test: "exit 0"
  pg_9.6_ssl:
    container_name: pg_9.6_ssl
    build: ./ssl/pg/9.6/
    ports:
      - "54326:5432"
    env_file: .env
    healthcheck:
      test: "exit 0"
  pg_10.x_ssl:
    container_name: pg_10.x_ssl
    build: ./ssl/pg/10.X/
    ports:
      - "54331:5432"
    env_file: .env
    healthcheck:
      test: "exit 0"
  pg_11.x_ssl:
    container_name: pg_11.x_ssl
    build: ./ssl/pg/11.X/
    ports:
      - "54332:5432"
    env_file: .env
    healthcheck:
      test: "exit 0"
  pg_12.x_ssl:
    container_name: pg_12.x_ssl
    build: ./ssl/pg/12.X/
    ports:
      - "54333:5432"
    env_file: .env
    healthcheck:
      test: "exit 0"
  mysql_5.7_ssl:
    container_name: mysql_5.7_ssl
    build: ./ssl/mysql/5.7/
    ports:
      - "33057:3306"
    env_file: .env
    command: [mysqld, --character-set-server=utf8, --collation-server=utf8_unicode_ci]
    healthcheck:
      test: "exit 0"
  mysql_8.0.x_ssl:
    container_name: mysql_8.0.x_ssl
    build: ./ssl/mysql/8.0.x/
    ports:
      - "33081:3306"
    env_file: .env
    command: [mysqld, --character-set-server=utf8, --collation-server=utf8_unicode_ci, --log-bin-trust-function-creators=true, --default_authentication_plugin=mysql_native_password]
    healthcheck:
      test: "exit 0"
  maria_10.3_ssl:
    container_name: maria_10.3_ssl
    build: ./ssl/maria/10.3/
    ports:
      - "33103:3306"
    env_file: .env
    command: [mysqld, --character-set-server=utf8, --collation-server=utf8_unicode_ci]
    healthcheck:
      test: "exit 0"
  mssql_2017_ssl:
      # jdbc:sqlserver://localhost:1433;databaseName=testdb;user=tester;password=My@Super@Secret
      container_name: mssql_2017_ssl
      privileged: true
      build: ./ssl/mssql/2017/
      hostname: mssql_2017
      ports:
        - "1433:1433"
      env_file: .env
      healthcheck:
        test: grep "Starting up database '${MSSQL_DB}'." /var/opt/mssql/log/errorlog || exit 1
        interval: 3m
        timeout: 10s
        retries: 5